import React, { ReactNode, useState } from 'react'
import 'flowbite';
import Head from 'next/head'
import { Header } from '../header'
import { Footer } from '../footer'

interface Props {
    children?: ReactNode,
    title?: any
    maxwidth?: string
}

export const Layout = ({ children, ...props }: Props) => {
    return (
        <>
            <Head>
                <title>{props.title}</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />
            <main {...props}>
                <div className={props.maxwidth + ' mx-auto my-5 p-10 rounded-lg justify-between bg-slate-50'}>
                    {children}
                </div >
            </main>
            <Footer />
        </>
    )
}
